name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy App to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GCP CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ai-search-puzzles

      - name: Authenticate Docker for Artifact Registry
        run: gcloud auth configure-docker us-east1-docker.pkg.dev --quiet

      - name: Deploy to Cloud Run
        run: ./deploy.sh
        env:
          GIT_COMMIT_SHA: ${{ github.sha }}
          GIT_REPO: ${{ github.repository }}
